<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GVijaySankar" failures="1" tests="3" name="test1" time="0.04" errors="0" timestamp="25 May 2024 07:56:44 GMT">
  <testcase classname="TestAutomation.Scripts.Suite.StudentCompleteTest" name="testFunction1" time="0.015">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at TestAutomation.Scripts.Suite.StudentCompleteTest.testFunction1(StudentCompleteTest.java:181)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testFunction1 -->
  <testcase classname="TestAutomation.Scripts.Suite.StudentCompleteTest" name="testFunction3" time="0.004"/>
  <testcase classname="TestAutomation.Scripts.Suite.StudentCompleteTest" name="testFunction2" time="0.0">
    <skipped/>
  </testcase> <!-- testFunction2 -->
</testsuite> <!-- test1 -->
