<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[27May2024]]>
    </line>
    <line>
      <![CDATA[27 May 2024]]>
    </line>
  </reporter-output>
  <suite started-at="2024-05-25T08:00:37Z" name="Default suite" finished-at="2024-05-25T08:00:39Z" duration-ms="2198">
    <groups>
      <group name="pallefunctional">
        <method signature="StudentCompleteTest.testFunction1()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" name="testFunction1" class="TestAutomation.Scripts.Suite.StudentCompleteTest"/>
        <method signature="StudentCompleteTest.testFunction2()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" name="testFunction2" class="TestAutomation.Scripts.Suite.StudentCompleteTest"/>
        <method signature="StudentCompleteTest.testFunction3()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" name="testFunction3" class="TestAutomation.Scripts.Suite.StudentCompleteTest"/>
      </group> <!-- pallefunctional -->
      <group name="vijay">
        <method signature="StudentCompleteTest.verifystudentDetailworkFlows()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" name="verifystudentDetailworkFlows" class="TestAutomation.Scripts.Suite.StudentCompleteTest"/>
      </group> <!-- vijay -->
    </groups>
    <test started-at="2024-05-25T08:00:37Z" name="Default test" finished-at="2024-05-25T08:00:39Z" duration-ms="2198">
      <class name="TestAutomation.Scripts.Suite.StudentCompleteTest">
        <test-method signature="testFunction1()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" started-at="2024-05-25T13:30:37Z" name="testFunction1" finished-at="2024-05-25T13:30:37Z" duration-ms="16" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at TestAutomation.Scripts.Suite.StudentCompleteTest.testFunction1(StudentCompleteTest.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFunction1 -->
        <test-method signature="verifystudentDetailworkFlows()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" started-at="2024-05-25T13:30:37Z" name="verifystudentDetailworkFlows" finished-at="2024-05-25T13:30:39Z" duration-ms="2159" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[27May2024]]>
            </line>
            <line>
              <![CDATA[27 May 2024]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifystudentDetailworkFlows -->
        <test-method signature="testFunction3()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" started-at="2024-05-25T13:30:39Z" name="testFunction3" finished-at="2024-05-25T13:30:39Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFunction3 -->
        <test-method signature="testFunction2()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825]" started-at="2024-05-25T13:30:39Z" name="testFunction2" finished-at="2024-05-25T13:30:39Z" depends-on-methods="TestAutomation.Scripts.Suite.StudentCompleteTest.testFunction1" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method StudentCompleteTest.testFunction2()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method StudentCompleteTest.testFunction2()[pri:0, instance:TestAutomation.Scripts.Suite.StudentCompleteTest@75b25825] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFunction2 -->
      </class> <!-- TestAutomation.Scripts.Suite.StudentCompleteTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
